# Builds the per-site plugin zips from the ONE source in ams-msa-popup/:
#
#   ams-msa-popup-infotainment/  + ams-msa-popup-infotainment.zip
#   ams-msa-popup-economy/       + ams-msa-popup-economy.zip
#   ams-msa-popup-education/     + ams-msa-popup-education.zip
#
# Each generated copy has the @AMS_SITE_PIN@ marker line replaced with
# define( 'AMS_MSA_POPUP_SITE', '<site>' ), hard-wiring which zone seed that
# zip carries (v2.4.1). EDIT ONLY ams-msa-popup/ — the per-site folders are
# build output and are overwritten on every run.
#
# The INNER folder in BOTH zips stays ams-msa-popup/ on purpose: that folder
# name is the plugin's identity to WordPress. A different inner name would
# install as a brand-new plugin and orphan the live settings + stats.
#
# Compress-Archive is NOT usable here: on Windows it writes backslash entry
# names, which WordPress's installer rejects. Entry names are therefore written
# by hand with forward slashes (one top-level folder holding the files).

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem

$root   = Split-Path -Parent $MyInvocation.MyCommand.Path
$srcDir = Join-Path $root 'ams-msa-popup'
$utf8   = New-Object System.Text.UTF8Encoding($false)  # no BOM; preserves the source's em dashes etc.

# Lint the source first - a syntax error reaching a live site would be found the slow way.
foreach ($f in @('ams-msa-popup.php', 'uninstall.php')) {
    $p = Join-Path $srcDir $f
    if (-not (Test-Path $p)) { throw "missing source file: $p" }
    & php -l $p | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "php -l failed for $f" }
}

$srcPhp = [System.IO.File]::ReadAllText((Join-Path $srcDir 'ams-msa-popup.php'), $utf8)
if ($srcPhp -notmatch '(?m)^// @AMS_SITE_PIN@') { throw 'source is missing the @AMS_SITE_PIN@ marker line' }

# Remove the old single-zip artifact so no ambiguous ams-msa-popup.zip lingers.
$oldZip = Join-Path $root 'ams-msa-popup.zip'
if (Test-Path $oldZip) { Remove-Item $oldZip }

foreach ($site in @('infotainment', 'economy', 'education')) {
    $outDir  = Join-Path $root "ams-msa-popup-$site"
    $zipPath = Join-Path $root "ams-msa-popup-$site.zip"

    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory $outDir | Out-Null }

    $pin = "define( 'AMS_MSA_POPUP_SITE', '$site' ); // GENERATED by build-msa-popup-zip.ps1 for the $($site.ToUpper()) zip - edit docs/wordpress/ams-msa-popup/, NOT this file."
    $pinned = $srcPhp -replace '(?m)^// @AMS_SITE_PIN@.*$', $pin

    [System.IO.File]::WriteAllText((Join-Path $outDir 'ams-msa-popup.php'), $pinned, $utf8)
    Copy-Item (Join-Path $srcDir 'uninstall.php') (Join-Path $outDir 'uninstall.php') -Force
    [System.IO.File]::WriteAllText((Join-Path $outDir 'README.txt'),
        "GENERATED build output for the $site site - do not edit.`r`nSource: docs/wordpress/ams-msa-popup/  Rebuild: build-msa-popup-zip.ps1`r`nUpload ams-msa-popup-$site.zip via Plugins -> Add Plugin -> Upload on the $site WordPress.`r`n", $utf8)

    & php -l (Join-Path $outDir 'ams-msa-popup.php') | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "php -l failed for generated $site copy" }

    if (Test-Path $zipPath) { Remove-Item $zipPath }
    $zip = [System.IO.Compression.ZipFile]::Open($zipPath, 'Create')
    try {
        foreach ($f in @('ams-msa-popup.php', 'uninstall.php')) {
            $entry  = $zip.CreateEntry("ams-msa-popup/$f", [System.IO.Compression.CompressionLevel]::Optimal)
            $stream = $entry.Open()
            $bytes  = [System.IO.File]::ReadAllBytes((Join-Path $outDir $f))
            $stream.Write($bytes, 0, $bytes.Length)
            $stream.Dispose()
        }
    } finally {
        $zip.Dispose()
    }

    $verify = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
    Write-Host "built $zipPath"
    $verify.Entries | ForEach-Object { Write-Host ("  {0}  ({1} bytes)" -f $_.FullName, $_.Length) }
    $verify.Dispose()
}
